name: Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Show Docker version
        run: docker --version
      - name: Prepare HAProxy root filesystem
        run: ./scripts/build-haproxy.sh
      - name: Display generated tree
        run: find build/rootfs -maxdepth 3 -type d -print
